name: "Push to main ✨"

on:
  push:
    branches:
      - main

jobs:
  test:
    name: 'Run tests 🧪'
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    name: 'Release 🚀'
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: myparcelnl/actions/yarn-install@v3
        with:
          node-version: 20

      - name: 'Build'
        shell: bash
        run: yarn build

      - run: npx -q semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
