name: "Push to main ✨"

on:
  push:
    branches:
      - main

jobs:
  test:
    name: 'Run tests 🧪'
    uses: edielemoine/google-sheets-translations-importer/.github/workflows/test.yml@main
    secrets: inherit

  release:
    name: 'Release 🚀'
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: '**/.github/workflows/push.yml'

      - run: npm i --no-save semantic-release @semantic-release/git

      - run: npx -q semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
