name: "Push to main ✨"

on:
  push:
    branches:
      - main

jobs:
  test:
    name: 'Run tests 🧪'
    uses: edielemoine/google-sheets-translations-importer/.github/workflows/test.yml@main
    secrets: inherit

  release:
    name: 'Release 🚀'
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false


      - name: 'Set up Node'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Set up pnpm'
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.7.0
          run_install: false

      - name: 'Get pnpm store directory'
        id: pnpm-cache
        shell: bash
        run: |
          echo "::set-output name=dir::$(pnpm store path)"

      - name: 'Prepare pnpm cache'
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 'Install pnpm dependencies'
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: 'Build'
        shell: bash
        run: pnpm build

      - run: npx -q semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
