name: 'Run tests 🧪'

on:
  workflow_call:

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 14, 16, 18, 20 ]
    env:
      MAIN_NODE_VERSION: 20
    steps:
      - uses: actions/checkout@v3

      - uses: myparcelnl/actions/yarn-install@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Run tests without coverage'
        if: env.MAIN_NODE_VERSION != matrix.node-version
        run: |
          yarn run test

      - name: 'Run tests with coverage'
        if: env.MAIN_NODE_VERSION == matrix.node-version
        run: |
          yarn run test:coverage

      - name: 'Upload coverage'
        if: env.MAIN_NODE_VERSION == matrix.node-version
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
